// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.xelerator.service.core;


public class ErrorDTOBuilder extends ErrorDTOBuilderBase<ErrorDTOBuilder> {
	public static ErrorDTOBuilder errorDTO() {
		return new ErrorDTOBuilder();
	}

	public ErrorDTOBuilder() {
		super(new ErrorDTO());
	}

	public ErrorDTO build() {
		return getInstance();
	}
}

class ErrorDTOBuilderBase<GeneratorT extends ErrorDTOBuilderBase<GeneratorT>> {
	private ErrorDTO instance;

	protected ErrorDTOBuilderBase(ErrorDTO aInstance) {
		instance = aInstance;
	}

	protected ErrorDTO getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withErrorCode(String aValue) {
		instance.setErrorCode(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withErrorMessage(String aValue) {
		instance.setErrorMessage(aValue);

		return (GeneratorT) this;
	}



	@SuppressWarnings("unchecked")
	public GeneratorT withErrorSubStatusCode(String aValue) {
		instance.setErrorSubStatusCode(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withErrorSubStatusMessage(String aValue) {
		instance.setErrorSubStatusMessage(aValue);

		return (GeneratorT) this;
	}
}
