package com.xelerator.service.core;

public enum OrderWorkFlowName {

	PLACE_ORDER, UPDATE_ORDER, CANCEL_ORDER, REFUND_ORDER, CHARGE_ORDER, STORE_ACCEPT_ORDER, STORE_REJECT_ORDER, STORE_PREPARING_ORDER, READY_TO_PICK_ORDER, DRIVER_PICKED_ORDER, DRIVER_DELIVERED_ORDER, DRIVER_DECLINED_ORDER, DRIVER_ACCEPTED_ORDER, DRIVER_IN_TRANSIT_TO_STORE, DRIVER_IN_TRANSIT_TO_CUSTOMER, NOTIFY_DRVR_ABOUT_ORDER, ADJUST_ORDER_ITEMS, RE_AUTHORIZE, STORE_ACCEPT_ORDER_BY_SHIPMENT, STORE_PREPARING_ORDER_BY_SHIPMENT, READY_TO_PICK_ORDER_BY_SHIPMENT, STORE_REJECT_ORDER_BY_SHIPMENT, DRIVER_IN_TRANSIT_TO_STORE_SHIPMENT, DRIVER_PICKED_ORDER_SHIPMENT

}
